# Generated by Django 3.1.1 on 2020-12-01 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 7, 10, 22, 841463, tzinfo=utc), verbose_name='date published'),
        ),
    ]
