# Generated by Django 3.1.1 on 2020-12-01 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201117_1343'),
        ('blog', '0003_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='posts', to='polls.Category'),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ManyToManyField(related_name='posts', to='polls.Topic'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 7, 28, 9, 132574, tzinfo=utc), verbose_name='date published'),
        ),
    ]
