# Generated by Django 3.1.1 on 2020-12-01 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201130_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 7, 29, 1, 324271, tzinfo=utc), verbose_name='date published'),
        ),
    ]
