# Generated by Django 3.1.1 on 2020-12-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201201_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(default='Uncategorized', related_name='posts', to='blog.Category'),
        ),
    ]
