# Generated by Django 3.1.1 on 2020-11-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201117_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(related_name='questions', to='polls.Category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ManyToManyField(related_name='questions', to='polls.Topic'),
        ),
    ]
